### ISSUE TITLE
Parsing of small plantuml fails on (presumably) missing visibility

### ISSUE THREAD

**Issue by JoshuaBehrens** [tasuku43/puml-parser-php#11]
I was looking into the parsing abilities of your changes in 2.1. It looks quite promising to me. It failed though to parse this file:

```
@startuml

hide empty methods

package Heptacom\HeptaConnect\Playground\Dataset {
    class Cap {
        + type : CapType
    }
}
@enduml
```

It fails with this stacktrace:

```
InvalidArgumentException: 

vendor/puml2php/puml-parser/src/Lexer/Token/Tokens.php:36
vendor/puml2php/puml-parser/src/Lexer/Token/Tokens.php:50
vendor/puml2php/puml-parser/src/Parser/Parser.php:149
vendor/puml2php/puml-parser/src/Parser/Parser.php:73
vendor/puml2php/puml-parser/src/Parser/Parser.php:114
vendor/puml2php/puml-parser/src/Parser/Parser.php:68
vendor/puml2php/puml-parser/src/Parser/Parser.php:50
```

I can follow the stacktrace but the exception is not helpful to understand where the tokenizing begins to fail. So the best would be to solve these two steps:

1. have a understandable error message. There are already exceptions that can tell exact positions in uml code (I saw some related to #10  ) . Maybe we can get this in there as well
2. understand why the above plantuml code fails and fix either the incoming uml code or tokenizer

**Comment by tasuku43** [comment]
https://github.com/tasuku43/puml-parser-php/pull/14 Fixed a problem that caused an infinite loop when property type information immediately preceded the closing parentheses.

**Comment by JoshuaBehrens** [comment]
Thank you for the quick release after your fix @tasuku43 I will have a look :)
