### ISSUE TITLE
How to install and use puml-parser-php on Windows-10?

### ISSUE THREAD

**Issue by it19862** [tasuku43/puml-parser-php#19]
I use
- Windows-10.
- OpenServer.
I'm starting to learn php.

How do I install and use puml-parser-php on Windows-10?
Do I need to install plantuml?

**Comment by it19862** [comment]
I created a folder in OpenServer: `c:\OpenServer\domains\puml-parser-php`.
I opened the console in OpenServer.
I executed the command `cd c:\OpenServer\domains\puml-parser-php`
I executed the command `composer require puml2php/puml-parser`
I got folders and files.
`vendor\`
`composer.lock`
`composer.json`

What should I do next?

**Comment by tasuku43** [comment]
@it19862 

Thanks for using it.

> Do I need to install plantuml?

You do not need to INSTALL plantuml for this library.
If your goal is to run plantuml, this library may not be the right application for you. What kind of functionality do you want to implement? :)

Please refer to [overview](https://github.com/tasuku43/puml-parser-php#overview) for more information on the use of this library.

---

> I got folders and files.
vendor
composer.lock
composer.json

Assuming your goal is to parse the plantuml file, the next step would be something like this.

- Create the plantuml file.
  - Refer to the sample in [Usage](https://github.com/tasuku43/puml-parser-php#usage)
- Perform analysis on the plantuml file as follows
  - ```php
     $lexer = new Lexer(PumlTokenizer::newInstance());
     $parser = new Parser($lexer);
     $ast = $parser->parse(__DIR__ . '/sample.puml');
    ```
- Using the parsed results, implement the functionality you want to achieve
