### ISSUE TITLE
Missing properties/fields

### ISSUE THREAD

**Issue by JoshuaBehrens** [tasuku43/puml-parser-php#6]
I really like to write a code generator with this library but your parser does not read the fields yet with it :/ With your package it would be possible to use php only to work with plantuml files. I watch this repo and maybe I can switch from xmi to this package :)

**Comment by tasuku43** [comment]
@JoshuaBehrens 
I'm glad you like it! We are thinking of supporting properties and fields as well.
I'll let you know via this issue when it's ready.

**Comment by tasuku43** [comment]
@JoshuaBehrens 

Parsing of properties is now supported.

- https://github.com/tasuku43/puml-parser-php/pull/7

However, we have not yet been able to support the type information specified for properties.
I plan to support the above in the future:)

**Comment by JoshuaBehrens** [comment]
Woop woop :) thank you very much. I will try it right away. Previously I was writing code based upon xmi but this was really missing with me as this is still experimental in plantuml. I can share later how I work with your library
